#!/usr/bin/env python3
"""Generate canonical directory manifests (96 + _template)."""

from __future__ import annotations

from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
DIR = ROOT / "directories"

CANONICAL_IDS = [
    "agensi",
    "agent-skill-exchange",
    "agent-skill-hub",
    "agentskill-sh",
    "agentskills-so",
    "aiagentsdirectory",
    "alexanderop-awesome-local-first",
    "allyourtech",
    "alternativeto",
    "anthropic-connectors",
    "anthropic-desktop-extensions",
    "anthropics-skills",
    "awesome-selfhosted",
    "awesomeclaude-ai-skills",
    "awesomeskills-dev",
    "betalist",
    "buda-marketplace",
    "capterra",
    "caramaschihg-awesome-ai-agents-2026",
    "ccplugins-awesome-claude-code-plugins",
    "chatgpt-gpt-store",
    "chatgpt-plugins-directory",
    "clau-de-shortlink",
    "claude-plugins-community",
    "claude-plugins-dev",
    "claude-plugins-official",
    "claudemarketplaces-com",
    "claudepluginhub",
    "claudeskills-info",
    "claudeskillsmarket",
    "clawhub-packages",
    "clawhub",
    "clawtools",
    "codex-local-marketplace",
    "composiohq-awesome-claude-skills",
    "cursor-directory",
    "cursor-marketplace",
    "cursorlist",
    "devhunt",
    "domain-specific-awesome",
    "duplicate-awesome-claude-code-clones",
    "e2b-dev-awesome-ai-agents",
    "futurepedia",
    "g2",
    "github-gh-skill-index",
    "glama-mcp",
    "grok-bot-plugins",
    "grok-build-marketplace",
    "grok-connectors",
    "guildskills-cursor-catalog",
    "hermes-agent-taps",
    "hesreallyhim-awesome-claude-code",
    "hol-awesome-codex-plugins",
    "indie-hackers-products",
    "jackyst0-awesome-agent-skills",
    "libhunt",
    "lobehub-skills-market",
    "localskills-sh",
    "mcp-directory",
    "mcp-so",
    "mcpmarket",
    "microsoft-cat",
    "moltbook",
    "nanoclaw-skills",
    "nanoclaw-templates",
    "official-codex-plugin-directory",
    "official-mcp-registry",
    "openai-plugins-github",
    "openai-skills",
    "openalternative",
    "patrickjs-awesome-cursorrules",
    "plaintextaccounting-org",
    "product-hunt",
    "pulsemcp",
    "punkpeye-awesome-mcp-servers",
    "saashub",
    "sanjeed5-awesome-cursor-rules-mdc",
    "schickling-awesome-local-first",
    "skillhub-club",
    "skills-re",
    "skills-sh",
    "skillsdirectory-co",
    "skillsdirectory-com",
    "skillsmp",
    "skillsplayground",
    "skly",
    "slashdot",
    "smithery",
    "taaft",
    "tonsofskills",
    "toolify-ai",
    "travisvn-awesome-claude-skills",
    "uneed",
    "voltagent-awesome-agent-skills",
    "voltagent-awesome-openclaw-skills",
    "vskill",
]

SPLITS_SKILLS_IDS = {
    "skills-re",
    "skillsplayground",
    "agentskill-sh",
    "github-gh-skill-index",
    "localskills-sh",
    "skills-sh",
    "vskill",
    "skillsdirectory-com",
}


def stub(
    id_: str,
    name: str,
    description: str,
    status: str = "wait",
    access_class: str = "web_form",
    url: str = "",
    listing_unit: str = "either",
    splits_skills: bool = False,
    notes: str = "Manifest stub — verify submission URL, access requirements, and listing_unit before setting status: active.",
    catalog_repo: str = "",
    catalog_path: str = "",
    **extra,
) -> dict:
    access: dict = {
        "class": access_class,
        "notes": notes.strip(),
    }
    if url:
        access["url"] = url
    if catalog_repo:
        access["catalog_repo"] = catalog_repo
    if catalog_path:
        access["catalog_path"] = catalog_path
    m = {
        "id": id_,
        "name": name,
        "description": description.strip(),
        "status": status,
        "access": access,
        "listing_unit": listing_unit,
        "splits_skills": splits_skills,
    }
    m.update(extra)
    return m


VERIFIED: dict[str, dict] = {
    "cursor-directory": stub(
        "cursor-directory",
        "cursor.directory",
        "Community discovery for Cursor plugins, MCP servers, rules, skills, and agents. Auto-detects from public GitHub repo URL.",
        status="active",
        url="https://cursor.directory/plugins/new",
        listing_unit="either",
        hosts=["cursor"],
        item_types=["skill", "plugin", "mcp", "rules", "agents"],
        install_guidance="Recommend Cursor Customize / Plugins or team marketplace import — not npx skills add.",
        references=[
            {"label": "Submit", "url": "https://cursor.directory/plugins/new"},
            {"label": "Cursor plugins docs", "url": "https://cursor.com/docs/plugins"},
        ],
        tags=["cursor", "community"],
        notes="Sign in with GitHub or Google. No catalog repo to clone.",
    ),
    "cursor-marketplace": stub(
        "cursor-marketplace",
        "Cursor Marketplace (official)",
        "Anysphere-reviewed official Cursor Marketplace for flagship plugins.",
        status="active",
        url="https://cursor.com/marketplace/publish",
        listing_unit="plugin",
        hosts=["cursor"],
        item_types=["plugin", "skill", "mcp"],
        install_guidance="Users install from Cursor Marketplace (Customize → Plugins).",
        references=[
            {"label": "Publish", "url": "https://cursor.com/marketplace/publish"},
            {"label": "Docs", "url": "https://cursor.com/docs/plugins"},
        ],
        tags=["cursor", "official", "reviewed"],
        notes="Manual review. One plugin per submission.",
    ),
    "anthropic-connectors": stub(
        "anthropic-connectors",
        "Anthropic Connectors Directory (MCP)",
        "Anthropic directory for MCP connectors, MCPB desktop extensions, and MCP Apps.",
        status="active",
        url="https://platform.claude.com/connectors/submit",
        listing_unit="product",
        hosts=["claude"],
        item_types=["mcp"],
        install_guidance="Users enable connectors from Claude.ai, Desktop, Claude Code, or Cowork.",
        references=[
            {"label": "Connectors docs", "url": "https://docs.anthropic.com/en/docs/connectors"},
        ],
        tags=["claude", "mcp", "official"],
        notes="Team/Enterprise org often required for claude.ai admin portal; Console paths for individuals.",
    ),
    "anthropic-desktop-extensions": stub(
        "anthropic-desktop-extensions",
        "Anthropic MCP desktop extensions",
        "Submission path for MCPB desktop extension connectors (distinct from remote MCP connector portal).",
        status="wait",
        listing_unit="product",
        hosts=["claude"],
        item_types=["mcp"],
        notes="Verify current Anthropic desktop extension submission form URL and requirements.",
    ),
    "claude-plugins-official": stub(
        "claude-plugins-official",
        "Claude Code Plugins Directory (official marketplace)",
        "Anthropic curated claude-plugins-official marketplace surfaced in Claude Code /plugins.",
        status="active",
        url="https://platform.claude.com/plugins/submit",
        listing_unit="plugin",
        hosts=["claude"],
        item_types=["plugin", "skill", "mcp", "commands", "agents"],
        install_guidance="Users install from Claude Code /plugins or Cowork plugin browser.",
        references=[
            {"label": "Submit (Console)", "url": "https://platform.claude.com/plugins/submit"},
            {"label": "claude-plugins-official", "url": "https://github.com/anthropics/claude-plugins-official"},
        ],
        tags=["claude", "official"],
        notes="Public GitHub repo required. Run claude plugin validate before submit.",
    ),
    "claude-plugins-community": stub(
        "claude-plugins-community",
        "Claude plugins community catalog",
        "Community plugin catalog synced into Claude Code Discover tab after in-app submission review.",
        status="active",
        url="https://clau.de/plugin-directory-submission",
        listing_unit="plugin",
        hosts=["claude"],
        item_types=["plugin", "skill", "mcp"],
        install_guidance="Install via Claude Code plugin marketplace after approval.",
        references=[
            {"label": "Submission shortlink", "url": "https://clau.de/plugin-directory-submission"},
        ],
        tags=["claude", "community"],
        notes="Automated review; approved plugins pinned into anthropics/claude-plugins-community (nightly sync).",
    ),
    "clau-de-shortlink": stub(
        "clau-de-shortlink",
        "clau.de plugin directory submission",
        "Short URL redirect to Claude plugin directory submission form.",
        status="active",
        url="https://clau.de/plugin-directory-submission",
        listing_unit="plugin",
        hosts=["claude"],
        item_types=["plugin"],
        notes="Alias/entry point for claude-plugins-community submission flow.",
    ),
    "chatgpt-plugins-directory": stub(
        "chatgpt-plugins-directory",
        "OpenAI Plugins Directory (ChatGPT / Codex)",
        "OpenAI Plugins Directory for ChatGPT and Codex plugins (skills, MCP, optional UI).",
        status="wait",
        url="https://platform.openai.com/plugins",
        listing_unit="plugin",
        hosts=["chatgpt", "codex"],
        item_types=["plugin", "skill", "mcp"],
        notes="Verified individual/business and manual review typically required. Confirm current portal policy.",
    ),
    "chatgpt-gpt-store": stub(
        "chatgpt-gpt-store",
        "ChatGPT GPT Store",
        "OpenAI GPT Store for custom GPTs (distinct from Codex/ChatGPT Plugins Directory for agent skills).",
        status="wait",
        listing_unit="product",
        hosts=["chatgpt"],
        item_types=["skill"],
        notes="GPT Store is not the same as agent SKILL.md directories — confirm fit before listing.",
    ),
    "skills-sh": stub(
        "skills-sh",
        "skills.sh",
        "Open agent skills ecosystem leaderboard and registry; repo import may fan out per SKILL.md.",
        status="active",
        url="https://skills.sh",
        access_class="auto_index",
        listing_unit="skill",
        splits_skills=True,
        hosts=["cross-platform"],
        item_types=["skill"],
        install_guidance="Prefer host marketplace/plugin install; CLI is secondary.",
        references=[{"label": "skills.sh", "url": "https://skills.sh"}],
        tags=["registry", "splits-skills"],
        notes="Skip for bundled plugins unless user opts into per-skill cards.",
    ),
    "skills-re": stub(
        "skills-re",
        "skills.re (Agent Skill Registry)",
        "Agent-agnostic registry; GitHub import may register multiple skills per repo.",
        status="active",
        url="https://skills.re/submit",
        listing_unit="skill",
        splits_skills=True,
        hosts=["cross-platform", "claude", "codex"],
        item_types=["skill"],
        references=[
            {"label": "Submit", "url": "https://skills.re/submit"},
            {"label": "FAQ", "url": "https://skills.re/faq"},
        ],
        tags=["registry", "splits-skills"],
        notes="Excludes dist/ on import. Skip for bundled plugins unless per-skill opt-in.",
    ),
    "skillsplayground": stub(
        "skillsplayground",
        "Skills Playground",
        "Community directory for Claude Code skills/plugins; auto-detects from GitHub URL.",
        status="active",
        url="https://skillsplayground.com/submit/",
        listing_unit="skill",
        splits_skills=True,
        hosts=["claude"],
        item_types=["skill", "plugin"],
        references=[{"label": "Submit", "url": "https://skillsplayground.com/submit/"}],
        tags=["claude", "splits-skills"],
    ),
    "agentskill-sh": stub(
        "agentskill-sh",
        "agentskill.sh",
        "Large agent skills directory/marketplace with quality and security scoring.",
        status="active",
        url="https://agentskill.sh",
        listing_unit="skill",
        splits_skills=True,
        hosts=["cross-platform", "claude", "cursor", "copilot"],
        item_types=["skill"],
        references=[{"label": "agentskill.sh", "url": "https://agentskill.sh"}],
        tags=["registry", "splits-skills"],
    ),
    "github-gh-skill-index": stub(
        "github-gh-skill-index",
        "GitHub gh skill index",
        "GitHub-native skill discovery/publishing via gh skill in GitHub CLI.",
        status="active",
        access_class="cli_publish",
        url="https://cli.github.com/manual/gh_skill",
        listing_unit="skill",
        splits_skills=True,
        hosts=["copilot", "claude", "cursor", "codex", "gemini", "cross-platform"],
        item_types=["skill"],
        references=[
            {"label": "gh skill manual", "url": "https://cli.github.com/manual/gh_skill"},
            {"label": "Changelog", "url": "https://github.blog/changelog/2026-04-16-manage-agent-skills-with-github-cli/"},
        ],
        tags=["github", "cli", "splits-skills"],
        notes="Use gh skill publish after approval. Skip for bundled plugins unless per-skill opt-in.",
    ),
    "localskills-sh": stub(
        "localskills-sh",
        "localskills.sh",
        "Team skills/rules registry; one skill slug per publish unit.",
        status="active",
        url="https://localskills.sh",
        listing_unit="skill",
        splits_skills=True,
        hosts=["cross-platform", "cursor", "claude"],
        item_types=["skill", "rules"],
        references=[
            {"label": "Site", "url": "https://localskills.sh"},
            {"label": "Docs", "url": "https://docs.localskills.sh/getting-started/"},
        ],
        tags=["registry", "team", "splits-skills"],
    ),
    "vskill": stub(
        "vskill",
        "vSkill (verified-skill.com)",
        "Verified skill registry with automated security scanning from public GitHub repos.",
        status="active",
        access_class="cli_publish",
        url="https://verified-skill.com/docs/submitting",
        listing_unit="skill",
        splits_skills=True,
        hosts=["cross-platform"],
        item_types=["skill", "plugin"],
        references=[
            {"label": "Submitting", "url": "https://verified-skill.com/docs/submitting"},
        ],
        tags=["verified", "splits-skills"],
        notes="npx vskill submit owner/repo or web form. Scan locally first.",
    ),
    "skillsdirectory-com": stub(
        "skillsdirectory-com",
        "Skills Directory (skillsdirectory.com)",
        "Curated, manually reviewed agent skills directory.",
        status="active",
        url="https://www.skillsdirectory.com/submit",
        listing_unit="skill",
        splits_skills=True,
        hosts=["claude", "cross-platform"],
        item_types=["skill"],
        references=[
            {"label": "Submit", "url": "https://www.skillsdirectory.com/submit"},
            {"label": "About", "url": "https://www.skillsdirectory.com/about"},
        ],
        tags=["curated", "splits-skills"],
    ),
    "jackyst0-awesome-agent-skills": stub(
        "jackyst0-awesome-agent-skills",
        "awesome-agent-skills (JackyST0)",
        "Community awesome list of agent skills for Cursor, Claude Code, Copilot, etc.",
        status="active",
        access_class="github_pr",
        url="https://github.com/JackyST0/awesome-agent-skills",
        catalog_repo="JackyST0/awesome-agent-skills",
        catalog_path="README.md",
        listing_unit="either",
        hosts=["cross-platform"],
        item_types=["skill"],
        notes="PR to README. Use gh/API only; delete fork after merge/close.",
    ),
    "hesreallyhim-awesome-claude-code": stub(
        "hesreallyhim-awesome-claude-code",
        "awesome-claude-code (hesreallyhim)",
        "Curated Claude Code skills, hooks, plugins, MCP servers, and workflows.",
        status="active",
        access_class="github_pr",
        url="https://github.com/hesreallyhim/awesome-claude-code",
        catalog_repo="hesreallyhim/awesome-claude-code",
        catalog_path="README.md",
        listing_unit="either",
        hosts=["claude"],
        item_types=["skill", "plugin", "mcp"],
        notes="PR to README. Delete fork after merge/close.",
    ),
    "punkpeye-awesome-mcp-servers": stub(
        "punkpeye-awesome-mcp-servers",
        "awesome-mcp-servers (punkpeye)",
        "Community curated awesome list of MCP servers.",
        status="active",
        access_class="github_pr",
        url="https://github.com/punkpeye/awesome-mcp-servers",
        catalog_repo="punkpeye/awesome-mcp-servers",
        catalog_path="README.md",
        listing_unit="product",
        hosts=["cross-platform", "claude", "cursor"],
        item_types=["mcp"],
        notes="PR for MCP servers. Also consider anthropic-connectors for Claude connector listing.",
    ),
    "anthropics-skills": stub(
        "anthropics-skills",
        "anthropics/skills (official examples)",
        "Anthropic reference skills repository — not a third-party submission directory.",
        status="skip",
        access_class="invite_only",
        url="https://github.com/anthropics/skills",
        catalog_repo="anthropics/skills",
        listing_unit="skill",
        hosts=["claude", "cross-platform"],
        item_types=["skill"],
        notes="Reference examples only. Use claude-plugins-official or community registries for third-party listings.",
    ),
    "official-mcp-registry": stub(
        "official-mcp-registry",
        "Official MCP Registry",
        "Anthropic/OpenAI-backed official MCP server registry (modelcontextprotocol.io registry).",
        status="active",
        url="https://registry.modelcontextprotocol.io",
        listing_unit="product",
        hosts=["cross-platform", "claude", "chatgpt"],
        item_types=["mcp"],
        references=[{"label": "MCP Registry", "url": "https://registry.modelcontextprotocol.io"}],
        tags=["mcp", "official"],
        notes="Verify current publisher submission workflow on registry site.",
    ),
    "smithery": stub(
        "smithery",
        "Smithery",
        "MCP server registry and distribution platform.",
        status="active",
        url="https://smithery.ai",
        listing_unit="product",
        hosts=["cross-platform", "claude", "cursor"],
        item_types=["mcp"],
        references=[{"label": "Smithery", "url": "https://smithery.ai"}],
        tags=["mcp", "registry"],
    ),
    "glama-mcp": stub(
        "glama-mcp",
        "Glama MCP directory",
        "Glama.ai MCP server directory and rankings.",
        status="active",
        url="https://glama.ai/mcp/servers",
        listing_unit="product",
        hosts=["cross-platform"],
        item_types=["mcp"],
        references=[{"label": "Glama MCP", "url": "https://glama.ai/mcp/servers"}],
        tags=["mcp"],
    ),
    "pulsemcp": stub(
        "pulsemcp",
        "PulseMCP",
        "MCP server discovery and news directory.",
        status="active",
        url="https://www.pulsemcp.com",
        listing_unit="product",
        hosts=["cross-platform"],
        item_types=["mcp"],
        references=[{"label": "PulseMCP", "url": "https://www.pulsemcp.com"}],
        tags=["mcp"],
    ),
    "mcp-so": stub(
        "mcp-so",
        "mcp.so",
        "MCP server directory and community index.",
        status="active",
        url="https://mcp.so",
        listing_unit="product",
        hosts=["cross-platform"],
        item_types=["mcp"],
        references=[{"label": "mcp.so", "url": "https://mcp.so"}],
        tags=["mcp"],
    ),
    "patrickjs-awesome-cursorrules": stub(
        "patrickjs-awesome-cursorrules",
        "awesome-cursorrules (PatrickJS)",
        "Comprehensive Cursor rules collection (legacy .cursorrules; related to skills/rules discovery).",
        status="active",
        access_class="github_pr",
        url="https://github.com/PatrickJS/awesome-cursorrules",
        catalog_repo="PatrickJS/awesome-cursorrules",
        catalog_path="README.md",
        listing_unit="either",
        hosts=["cursor"],
        item_types=["rules", "skill"],
        notes="PR-based awesome list. Rules-focused; include only if target ships .mdc rules or SKILL.md.",
    ),
    "composiohq-awesome-claude-skills": stub(
        "composiohq-awesome-claude-skills",
        "awesome-claude-skills (ComposioHQ)",
        "Curated Claude skills list maintained by ComposioHQ.",
        status="active",
        access_class="github_pr",
        url="https://github.com/ComposioHQ/awesome-claude-skills",
        catalog_repo="ComposioHQ/awesome-claude-skills",
        catalog_path="README.md",
        listing_unit="either",
        hosts=["claude"],
        item_types=["skill"],
    ),
    "travisvn-awesome-claude-skills": stub(
        "travisvn-awesome-claude-skills",
        "awesome-claude-skills (travisvn)",
        "Community curated Claude skills awesome list.",
        status="active",
        access_class="github_pr",
        url="https://github.com/travisvn/awesome-claude-skills",
        catalog_repo="travisvn/awesome-claude-skills",
        catalog_path="README.md",
        listing_unit="either",
        hosts=["claude"],
        item_types=["skill"],
    ),
    "voltagent-awesome-agent-skills": stub(
        "voltagent-awesome-agent-skills",
        "awesome-agent-skills (VoltAgent)",
        "VoltAgent-maintained awesome agent skills list.",
        status="active",
        access_class="github_pr",
        url="https://github.com/VoltAgent/awesome-agent-skills",
        catalog_repo="VoltAgent/awesome-agent-skills",
        catalog_path="README.md",
        listing_unit="either",
        hosts=["cross-platform"],
        item_types=["skill"],
    ),
    "voltagent-awesome-openclaw-skills": stub(
        "voltagent-awesome-openclaw-skills",
        "awesome-openclaw-skills (VoltAgent)",
        "OpenClaw agent skills awesome list.",
        status="active",
        access_class="github_pr",
        url="https://github.com/VoltAgent/awesome-openclaw-skills",
        catalog_repo="VoltAgent/awesome-openclaw-skills",
        catalog_path="README.md",
        listing_unit="either",
        hosts=["other"],
        item_types=["skill"],
    ),
    "awesomeskills-dev": stub(
        "awesomeskills-dev",
        "awesomeskills.dev",
        "Cross-platform agent skills directory and discovery site.",
        status="wait",
        url="https://awesomeskills.dev",
        listing_unit="either",
        hosts=["cross-platform"],
        item_types=["skill"],
        notes="Verify submission workflow on awesomeskills.dev.",
    ),
    "openai-skills": stub(
        "openai-skills",
        "OpenAI skills documentation",
        "OpenAI platform skills/docs surface for Codex and ChatGPT agent skills.",
        status="wait",
        url="https://platform.openai.com/docs",
        listing_unit="either",
        hosts=["chatgpt", "codex"],
        item_types=["skill"],
        notes="Distinguish from chatgpt-plugins-directory. Verify current OpenAI skills publishing path.",
    ),
    "official-codex-plugin-directory": stub(
        "official-codex-plugin-directory",
        "Official Codex plugin directory",
        "OpenAI Codex plugin directory (shared Plugins Directory with ChatGPT as of 2026).",
        status="wait",
        url="https://platform.openai.com/plugins",
        listing_unit="plugin",
        hosts=["codex"],
        item_types=["plugin", "skill", "mcp"],
        notes="May overlap chatgpt-plugins-directory — confirm single submission path.",
    ),
    "codex-local-marketplace": stub(
        "codex-local-marketplace",
        "Codex local marketplace",
        "Local or project-scoped Codex plugin marketplace configuration.",
        status="wait",
        listing_unit="plugin",
        hosts=["codex"],
        item_types=["plugin"],
        notes="Verify Codex local marketplace.json / team import docs.",
    ),
    "guildskills-cursor-catalog": stub(
        "guildskills-cursor-catalog",
        "Guildskills Cursor catalog",
        "Community Cursor skills/plugins catalog (guildskills).",
        status="wait",
        listing_unit="either",
        hosts=["cursor"],
        item_types=["skill", "plugin"],
        notes="Verify guildskills submission URL and whether catalog is active.",
    ),
    "lobehub-skills-market": stub(
        "lobehub-skills-market",
        "LobeHub skills market",
        "LobeHub agent skills marketplace/discovery.",
        status="wait",
        url="https://lobehub.com",
        listing_unit="either",
        hosts=["cross-platform"],
        item_types=["skill"],
        notes="Verify LobeHub skills market submission process.",
    ),
    "skillsmp": stub(
        "skillsmp",
        "SkillsMP",
        "Agent skills marketplace/directory (skillsmp).",
        status="wait",
        listing_unit="either",
        hosts=["cross-platform"],
        item_types=["skill"],
        notes="Verify skillsmp.com submission workflow.",
    ),
    "skillhub-club": stub(
        "skillhub-club",
        "SkillHub Club",
        "Community skill hub and directory.",
        status="wait",
        listing_unit="either",
        hosts=["cross-platform"],
        item_types=["skill"],
        notes="Verify skillhub.club submission process.",
    ),
    "agentskills-so": stub(
        "agentskills-so",
        "agentskills.so",
        "Agent skills discovery/registry site.",
        status="wait",
        listing_unit="either",
        hosts=["cross-platform"],
        item_types=["skill"],
        notes="Verify agentskills.so listing submission.",
    ),
    "tonsofskills": stub(
        "tonsofskills",
        "Tons of Skills",
        "Agent skills discovery directory.",
        status="wait",
        listing_unit="either",
        hosts=["cross-platform"],
        item_types=["skill"],
        notes="Verify tonsofskills submission URL.",
    ),
    "ccplugins-awesome-claude-code-plugins": stub(
        "ccplugins-awesome-claude-code-plugins",
        "awesome-claude-code-plugins (ccplugins)",
        "Curated Claude Code plugins awesome list.",
        status="active",
        access_class="github_pr",
        url="https://github.com/ccplugins/awesome-claude-code-plugins",
        catalog_repo="ccplugins/awesome-claude-code-plugins",
        catalog_path="README.md",
        listing_unit="plugin",
        hosts=["claude"],
        item_types=["plugin"],
    ),
    "hol-awesome-codex-plugins": stub(
        "hol-awesome-codex-plugins",
        "awesome-codex-plugins (hol)",
        "Curated Codex plugins awesome list.",
        status="active",
        access_class="github_pr",
        url="https://github.com/hol/awesome-codex-plugins",
        catalog_repo="hol/awesome-codex-plugins",
        catalog_path="README.md",
        listing_unit="plugin",
        hosts=["codex"],
        item_types=["plugin"],
        notes="Verify repo exists and contribution guidelines.",
    ),
    "e2b-dev-awesome-ai-agents": stub(
        "e2b-dev-awesome-ai-agents",
        "awesome-ai-agents (e2b-dev)",
        "E2B-maintained awesome AI agents list (may include skills/tools).",
        status="active",
        access_class="github_pr",
        url="https://github.com/e2b-dev/awesome-ai-agents",
        catalog_repo="e2b-dev/awesome-ai-agents",
        catalog_path="README.md",
        listing_unit="either",
        hosts=["cross-platform"],
        item_types=["skill", "plugin", "agents"],
    ),
    "caramaschihg-awesome-ai-agents-2026": stub(
        "caramaschihg-awesome-ai-agents-2026",
        "awesome-ai-agents-2026",
        "2026 curated awesome AI agents list.",
        status="wait",
        access_class="github_pr",
        listing_unit="either",
        hosts=["cross-platform"],
        item_types=["agents", "skill"],
        notes="Verify GitHub repo URL for caramaschihg/awesome-ai-agents-2026.",
    ),
    "duplicate-awesome-claude-code-clones": stub(
        "duplicate-awesome-claude-code-clones",
        "awesome-claude-code clones (dedupe)",
        "Meta entry: prefer hesreallyhim-awesome-claude-code; avoid duplicate PRs to forked awesome lists.",
        status="skip",
        listing_unit="either",
        hosts=["claude"],
        item_types=["skill", "plugin"],
        notes="Use hesreallyhim-awesome-claude-code as canonical Claude awesome list unless user names a specific clone.",
    ),
    "domain-specific-awesome": stub(
        "domain-specific-awesome",
        "Domain-specific awesome lists",
        "Placeholder for vertical awesome lists (DevOps, security, data, etc.) — pick the specific list manifest instead.",
        status="skip",
        listing_unit="either",
        hosts=["cross-platform"],
        item_types=["skill"],
        notes="Do not file here. Select a concrete awesome-list manifest (e.g. composiohq-awesome-claude-skills).",
    ),
    "hermes-agent-taps": stub(
        "hermes-agent-taps",
        "Hermes agent taps / skills hub",
        "Hermes agent third-party skill install paths and hub integrations.",
        status="wait",
        url="https://github.com/NousResearch/hermes-agent",
        listing_unit="skill",
        hosts=["other"],
        item_types=["skill"],
        notes="Hermes uses ~/.hermes/skills/ and hub installs — verify external listing vs hub publish.",
    ),
    "claude-plugins-dev": stub(
        "claude-plugins-dev",
        "claude-plugins.dev",
        "Third-party Claude plugins discovery site.",
        status="wait",
        listing_unit="plugin",
        hosts=["claude"],
        item_types=["plugin"],
        notes="Verify claude-plugins.dev submission workflow.",
    ),
    "claudemarketplaces-com": stub(
        "claudemarketplaces-com",
        "claudemarketplaces.com",
        "Third-party Claude marketplaces aggregator/directory.",
        status="wait",
        listing_unit="plugin",
        hosts=["claude"],
        item_types=["plugin"],
        notes="Verify listing submission process.",
    ),
    "claudepluginhub": stub(
        "claudepluginhub",
        "Claude Plugin Hub",
        "Community Claude plugin hub/directory.",
        status="wait",
        listing_unit="plugin",
        hosts=["claude"],
        item_types=["plugin"],
    ),
    "claudeskills-info": stub(
        "claudeskills-info",
        "claudeskills.info",
        "Claude skills information/directory site.",
        status="wait",
        listing_unit="skill",
        hosts=["claude"],
        item_types=["skill"],
    ),
    "claudeskillsmarket": stub(
        "claudeskillsmarket",
        "Claude Skills Market",
        "Claude skills marketplace/directory.",
        status="wait",
        listing_unit="skill",
        hosts=["claude"],
        item_types=["skill"],
    ),
    "skillsdirectory-co": stub(
        "skillsdirectory-co",
        "skillsdirectory.co",
        "Alternate skillsdirectory TLD — verify relationship to skillsdirectory.com.",
        status="wait",
        listing_unit="skill",
        hosts=["cross-platform"],
        item_types=["skill"],
        notes="May redirect or duplicate skillsdirectory-com; verify before filing.",
    ),
    "nanoclaw-skills": stub(
        "nanoclaw-skills",
        "Nanoclaw skills",
        "Nanoclaw agent skills catalog/templates ecosystem.",
        status="wait",
        listing_unit="skill",
        hosts=["other"],
        item_types=["skill"],
        notes="Verify nanoclaw skills publish path.",
    ),
    "nanoclaw-templates": stub(
        "nanoclaw-templates",
        "Nanoclaw templates",
        "Nanoclaw agent templates catalog.",
        status="wait",
        listing_unit="skill",
        hosts=["other"],
        item_types=["skill"],
    ),
    "clawhub": stub(
        "clawhub",
        "ClawHub",
        "OpenClaw/Claw ecosystem hub for skills and packages.",
        status="wait",
        listing_unit="either",
        hosts=["other"],
        item_types=["skill", "plugin"],
        notes="Verify ClawHub submission workflow for OpenClaw skills.",
    ),
    "clawhub-packages": stub(
        "clawhub-packages",
        "ClawHub packages",
        "Package index within ClawHub ecosystem.",
        status="wait",
        listing_unit="product",
        hosts=["other"],
        item_types=["plugin", "skill"],
    ),
    "clawtools": stub(
        "clawtools",
        "ClawTools",
        "Tools directory for Claw/OpenClaw agent ecosystem.",
        status="wait",
        listing_unit="either",
        hosts=["other"],
        item_types=["skill"],
    ),
    "moltbook": stub(
        "moltbook",
        "Moltbook",
        "Agent skills/tools directory (moltbook).",
        status="wait",
        listing_unit="either",
        hosts=["cross-platform"],
        item_types=["skill"],
    ),
    "microsoft-cat": stub(
        "microsoft-cat",
        "Microsoft CAT",
        "Microsoft Customer Advisory Team resources — verify agent skills/plugin listing relevance.",
        status="wait",
        listing_unit="product",
        hosts=["copilot"],
        item_types=["skill", "plugin"],
        notes="Confirm whether this is a public submission directory or internal catalog.",
    ),
    "openai-plugins-github": stub(
        "openai-plugins-github",
        "openai/plugins (historical)",
        "Historical OpenAI plugins GitHub examples — not a live submission directory.",
        status="skip",
        access_class="invite_only",
        url="https://github.com/openai/plugins",
        listing_unit="plugin",
        hosts=["chatgpt"],
        item_types=["plugin"],
        notes="Reference only. Use chatgpt-plugins-directory for current submissions.",
    ),
    "grok-connectors": stub(
        "grok-connectors",
        "Grok connectors",
        "xAI Grok connector directory (if published).",
        status="wait",
        listing_unit="product",
        hosts=["other"],
        item_types=["mcp"],
        notes="Verify xAI Grok connector submission portal.",
    ),
    "grok-build-marketplace": stub(
        "grok-build-marketplace",
        "Grok build marketplace",
        "xAI Grok build/marketplace for tools and plugins.",
        status="wait",
        listing_unit="plugin",
        hosts=["other"],
        item_types=["plugin", "skill"],
    ),
    "grok-bot-plugins": stub(
        "grok-bot-plugins",
        "Grok bot plugins",
        "Grok bot plugin ecosystem directory.",
        status="wait",
        listing_unit="plugin",
        hosts=["other"],
        item_types=["plugin"],
    ),
    "product-hunt": stub(
        "product-hunt",
        "Product Hunt",
        "Product launch platform (marketing surface, not a skill directory).",
        status="wait",
        url="https://www.producthunt.com",
        listing_unit="product",
        hosts=["cross-platform"],
        item_types=["plugin", "skill"],
        notes="Launch/marketing only — not a technical skill index. Optional credibility play.",
    ),
    "betalist": stub(
        "betalist",
        "BetaList",
        "Startup beta launch directory.",
        status="wait",
        url="https://betalist.com",
        listing_unit="product",
        notes="Marketing surface; not an agent skill catalog.",
    ),
    "g2": stub(
        "g2",
        "G2",
        "Software reviews marketplace.",
        status="wait",
        url="https://www.g2.com",
        listing_unit="product",
        notes="SaaS reviews — only if shipping a productized agent tool with G2 category.",
    ),
    "capterra": stub(
        "capterra",
        "Capterra",
        "Software directory and reviews.",
        status="wait",
        url="https://www.capterra.com",
        listing_unit="product",
        notes="Marketing/reviews surface.",
    ),
    "alternativeto": stub(
        "alternativeto",
        "AlternativeTo",
        "Software alternatives directory.",
        status="wait",
        url="https://alternativeto.net",
        listing_unit="product",
        notes="Discovery/marketing; not skill-specific.",
    ),
    "saashub": stub(
        "saashub",
        "SaaSHub",
        "SaaS alternatives and tools directory.",
        status="wait",
        url="https://www.saashub.com",
        listing_unit="product",
    ),
    "toolify-ai": stub(
        "toolify-ai",
        "Toolify.ai",
        "AI tools directory.",
        status="wait",
        url="https://www.toolify.ai",
        listing_unit="product",
        hosts=["cross-platform"],
        item_types=["skill", "plugin"],
    ),
    "futurepedia": stub(
        "futurepedia",
        "Futurepedia",
        "AI tools directory.",
        status="wait",
        url="https://www.futurepedia.io",
        listing_unit="product",
    ),
    "taaft": stub(
        "taaft",
        "There's An AI For That (TAAFT)",
        "AI tools directory.",
        status="wait",
        url="https://theresanaiforthat.com",
        listing_unit="product",
    ),
    "aiagentsdirectory": stub(
        "aiagentsdirectory",
        "AI Agents Directory",
        "General AI agents/tools directory.",
        status="wait",
        listing_unit="either",
        hosts=["cross-platform"],
        item_types=["agents", "skill"],
    ),
    "agensi": stub(
        "agensi",
        "Agensi",
        "AI agents directory/listing site.",
        status="wait",
        listing_unit="either",
        hosts=["cross-platform"],
        item_types=["agents"],
    ),
    "agent-skill-exchange": stub(
        "agent-skill-exchange",
        "Agent Skill Exchange",
        "Community agent skill exchange/directory.",
        status="wait",
        listing_unit="skill",
        hosts=["cross-platform"],
        item_types=["skill"],
    ),
    "agent-skill-hub": stub(
        "agent-skill-hub",
        "Agent Skill Hub",
        "Agent skill hub/directory.",
        status="wait",
        listing_unit="skill",
        hosts=["cross-platform"],
        item_types=["skill"],
    ),
    "awesome-selfhosted": stub(
        "awesome-selfhosted",
        "awesome-selfhosted",
        "Awesome self-hosted software list — only if MCP server is self-hostable infrastructure.",
        status="wait",
        access_class="github_pr",
        url="https://github.com/awesome-selfhosted/awesome-selfhosted",
        catalog_repo="awesome-selfhosted/awesome-selfhosted",
        catalog_path="README.md",
        listing_unit="product",
        hosts=["cross-platform"],
        item_types=["mcp"],
        notes="Include only for self-hosted MCP/server products.",
    ),
    "awesomeclaude-ai-skills": stub(
        "awesomeclaude-ai-skills",
        "awesomeclaude.ai skills",
        "awesomeclaude.ai skills index.",
        status="wait",
        listing_unit="skill",
        hosts=["claude"],
        item_types=["skill"],
    ),
    "alexanderop-awesome-local-first": stub(
        "alexanderop-awesome-local-first",
        "awesome-local-first (alexanderop)",
        "Local-first software awesome list.",
        status="wait",
        access_class="github_pr",
        listing_unit="product",
        hosts=["cross-platform"],
        notes="Only if target is local-first agent tooling.",
    ),
    "schickling-awesome-local-first": stub(
        "schickling-awesome-local-first",
        "awesome-local-first (schickling)",
        "Local-first software awesome list (schickling).",
        status="wait",
        access_class="github_pr",
        listing_unit="product",
        notes="Only if target is local-first agent tooling.",
    ),
    "allyourtech": stub(
        "allyourtech",
        "AllYourTech",
        "Tech tools directory.",
        status="wait",
        listing_unit="product",
    ),
    "buda-marketplace": stub(
        "buda-marketplace",
        "Buda Marketplace",
        "Third-party agent/plugin marketplace.",
        status="wait",
        listing_unit="plugin",
    ),
    "cursorlist": stub(
        "cursorlist",
        "CursorList",
        "Cursor tools/rules directory.",
        status="wait",
        listing_unit="either",
        hosts=["cursor"],
        item_types=["rules", "skill", "plugin"],
    ),
    "devhunt": stub(
        "devhunt",
        "DevHunt",
        "Developer tools launch platform.",
        status="wait",
        url="https://devhunt.org",
        listing_unit="product",
    ),
    "indie-hackers-products": stub(
        "indie-hackers-products",
        "Indie Hackers Products",
        "Indie Hackers product directory.",
        status="wait",
        url="https://www.indiehackers.com",
        listing_unit="product",
        notes="Marketing/community surface.",
    ),
    "libhunt": stub(
        "libhunt",
        "LibHunt",
        "Open source project discovery (awesome lists on LibHunt).",
        status="wait",
        url="https://www.libhunt.com",
        listing_unit="product",
    ),
    "openalternative": stub(
        "openalternative",
        "OpenAlternative",
        "Open source alternatives directory.",
        status="wait",
        url="https://openalternative.co",
        listing_unit="product",
    ),
    "plaintextaccounting-org": stub(
        "plaintextaccounting-org",
        "plaintextaccounting.org",
        "Plain text accounting ecosystem directory — niche; only for accounting-related agent skills.",
        status="skip",
        listing_unit="skill",
        notes="Domain-specific; skip unless target skill is accounting-related.",
    ),
    "slashdot": stub(
        "slashdot",
        "Slashdot",
        "Tech news — not an agent skill directory.",
        status="skip",
        listing_unit="product",
        notes="Press/marketing only if relevant.",
    ),
    "skly": stub(
        "skly",
        "Skly",
        "Skills/tools directory (skly).",
        status="wait",
        listing_unit="skill",
    ),
    "sanjeed5-awesome-cursor-rules-mdc": stub(
        "sanjeed5-awesome-cursor-rules-mdc",
        "awesome-cursor-rules-mdc (sanjeed5)",
        "Curated Cursor .mdc rules list.",
        status="active",
        access_class="github_pr",
        url="https://github.com/sanjeed5/awesome-cursor-rules-mdc",
        catalog_repo="sanjeed5/awesome-cursor-rules-mdc",
        catalog_path="README.md",
        listing_unit="either",
        hosts=["cursor"],
        item_types=["rules"],
    ),
    "mcp-directory": stub(
        "mcp-directory",
        "MCP Directory (generic)",
        "Generic MCP directory placeholder — prefer smithery, glama-mcp, pulsemcp, official-mcp-registry.",
        status="skip",
        listing_unit="product",
        item_types=["mcp"],
        notes="Use a concrete MCP manifest instead of this generic entry.",
    ),
    "mcpmarket": stub(
        "mcpmarket",
        "MCP Market",
        "MCP server marketplace.",
        status="wait",
        listing_unit="product",
        hosts=["cross-platform"],
        item_types=["mcp"],
    ),
    "uneed": stub(
        "uneed",
        "UNeed",
        "Startup/tools discovery (uneed.best).",
        status="wait",
        listing_unit="product",
    ),
}

# Remove typo fix block — no longer needed

def human_name(id_: str) -> str:
    return id_.replace("-", " ").title()


def main() -> None:
    assert len(CANONICAL_IDS) == 96, len(CANONICAL_IDS)

    # Remove non-canonical yaml files
    for path in DIR.glob("*.yaml"):
        if path.name == "_template.yaml":
            continue
        if path.stem not in CANONICAL_IDS:
            path.unlink()

    for id_ in CANONICAL_IDS:
        if id_ in VERIFIED:
            data = VERIFIED[id_]
        else:
            data = stub(
                id_,
                human_name(id_),
                f"Directory manifest for {id_}.",
            )

        # Enforce splits_skills canonical rule
        if id_ in SPLITS_SKILLS_IDS:
            data["splits_skills"] = True
            data["listing_unit"] = "skill"
        else:
            if data.get("splits_skills"):
                data["splits_skills"] = False

        data["id"] = id_
        path = DIR / f"{id_}.yaml"
        with path.open("w", encoding="utf-8") as f:
            yaml.dump(data, f, sort_keys=False, allow_unicode=True, default_flow_style=False)

    count = len(list(DIR.glob("*.yaml"))) - 1  # minus template
    print(f"Wrote {count} manifests (+ _template.yaml)")


if __name__ == "__main__":
    main()
